version: 2.1

orbs:
  maven: circleci/maven@1.0.3
  snyk: snyk/snyk@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          command: 'spring-boot:build-image'

#workflows:
#  maven_test:
#    jobs:
#      - maven/test # checkout, build, test, and upload test results
#          command: 'spring-boot:build-image'
#      - snyk/scan
#          docker-image-name: 'purpledobie/java-svc:cnb'
#          fail-on-issues: fail-on-issues
#          monitor-on-build: true
#          severity-threshold: high
#          token-variable: API_TOKEN
